title: Reuben Head # your name (or website title) here
logo: "/images/reubenhead.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <style text-align: justify;>>A dedicated and committed Web Design and Development
  graduate looking for a fulfilling career in the Information
  Technology sector, with an extensive background in military
  intelligence. Possess a Diploma in Web Design and Development
  from Whitecliffe, New Zealand. Highly focused with a passion
  to help people and find solutions to a variety of problems,
  no matter how difficult.
  <br><br>
  Currently working for Datacom as a Service Desk Analyst in
  Wellington, New Zealand.
  <br><br>
  </style>
  <a href="https://www.linkedin.com/in/reuben-head/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
